export interface Template {
  id: string;
  name: string;
  category: string;
  size: number;
  data: (string | null)[][];
}

export const COLOR_PALETTE = [
  '#FF6B9D',
  '#5DADE2',
  '#58D68D',
  '#F7DC6F',
  '#BB8FCE',
  '#FF8C42',
  '#E74C3C',
  '#3498DB',
  '#2ECC71',
  '#F39C12',
  '#9B59B6',
  '#1ABC9C',
];

const createTemplate = (
  id: string,
  name: string,
  category: string,
  size: number,
  data: (string | null)[][]
): Template => ({ id, name, category, size, data });

export const TEMPLATES: Template[] = [
  createTemplate('heart', '爱心', '基础', 16, [
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,'#FF6B9D','#FF6B9D',null,null,null,null,null,null,null,'#FF6B9D','#FF6B9D',null,null],
    [null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null],
    [null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null],
    [null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null],
    [null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null],
    [null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null],
    [null,null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,null],
    [null,null,null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,null,null],
    [null,null,null,null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,null,null,null],
    [null,null,null,null,null,null,'#FF6B9D','#FF6B9D','#FF6B9D','#FF6B9D',null,null,null,null,null,null],
    [null,null,null,null,null,null,null,'#FF6B9D','#FF6B9D',null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
  ]),
  createTemplate('star', '星星', '基础', 16, [
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,'#F7DC6F',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,'#F7DC6F','#F7DC6F','#F7DC6F',null,null,null,null,null,null,null],
    [null,null,null,null,null,'#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F',null,null,null,null,null,null],
    [null,null,null,null,'#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F',null,null,null,null],
    [null,null,null,'#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F','#F7DC6F',null,null,null],
    [null,null,null,null,null,null,null,'#F7DC6F',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,'#F7DC6F',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,'#F7DC6F','#FF8C42','#F7DC6F',null,null,null,null,null,null,null],
    [null,null,null,null,null,'#F7DC6F','#FF8C42','#FF8C42','#F7DC6F',null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
  ]),
  createTemplate('mushroom', '蘑菇', '自然', 16, [
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,'#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C',null,null,null],
    [null,null,null,'#E74C3C','#E74C3C','#FFFFFF','#FFFFFF','#E74C3C','#E74C3C','#FFFFFF','#FFFFFF','#E74C3C','#E74C3C','#E74C3C',null,null],
    [null,null,'#E74C3C','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#E74C3C',null],
    [null,null,'#E74C3C','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#E74C3C',null],
    [null,null,'#E74C3C','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#FFFFFF','#FFFFFF','#FFFFFF','#FFFFFF','#E74C3C','#E74C3C',null],
    [null,null,null,'#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C','#E74C3C',null,null],
    [null,null,null,null,null,null,'#F5DEB3','#F5DEB3',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,'#F5DEB3','#F5DEB3',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,'#F5DEB3','#F5DEB3','#F5DEB3','#F5DEB3',null,null,null,null,null,null,null],
    [null,null,null,null,null,'#F5DEB3','#F5DEB3','#F5DEB3','#F5DEB3',null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
  ]),
  createTemplate('cat', '猫脸', '动物', 16, [
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#333333','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#333333','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null],
    [null,null,'#FFE4C4','#FFE4C4','#FFB6C1','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFB6C1','#FFE4C4','#FFE4C4',null,null],
    [null,null,null,'#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4','#FFE4C4',null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
  ]),
  createTemplate('flower', '小花', '自然', 16, [
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,'#FF6B9D',null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,'#FF6B9D','#F7DC6F','#FF6B9D',null,null,null,null,null,null,null],
    [null,null,null,null,null,'#FF6B9D','#FF6B9D','#F7DC6F','#FF6B9D','#FF6B9D',null,null,null,null,null],
    [null,null,null,null,null,'#FF6B9D','#FF6B9D','#F7DC6F','#FF6B9D','#FF6B9D',null,null,null,null,null],
    [null,null,null,null,null,null,'#FF6B9D','#FF6B9D','#F7DC6F','#FF6B9D',null,null,null,null,null],
    [null,null,null,null,null,null,null,'#FF6B9D',null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,'#58D68D',null,null,null,null,null,null,null],
    [null,null,null,null,null,null,'#58D68D','#58D68D','#58D68D',null,null,null,null,null,null],
    [null,null,null,null,null,null,'#58D68D',null,'#58D68D',null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],
  ]),
];
